# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.models.inline_response_200_6_tags import InlineResponse2006Tags


class TestInlineResponse2006Tags(unittest.TestCase):
    """ InlineResponse2006Tags unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2006Tags(self):
        """
        Test InlineResponse2006Tags
        """
        model = postmark.models.inline_response_200_6_tags.InlineResponse2006Tags()


if __name__ == '__main__':
    unittest.main()
