# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.models.inline_response_200 import InlineResponse200


class TestInlineResponse200(unittest.TestCase):
    """ InlineResponse200 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200(self):
        """
        Test InlineResponse200
        """
        model = postmark.models.inline_response_200.InlineResponse200()


if __name__ == '__main__':
    unittest.main()
