# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.models.inline_response_200_7 import InlineResponse2007


class TestInlineResponse2007(unittest.TestCase):
    """ InlineResponse2007 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007(self):
        """
        Test InlineResponse2007
        """
        model = postmark.models.inline_response_200_7.InlineResponse2007()


if __name__ == '__main__':
    unittest.main()
