# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.apis.sending_api_api import SendingAPIApi


class TestSendingAPIApi(unittest.TestCase):
    """ SendingAPIApi unit test stubs """

    def setUp(self):
        self.api = postmark.apis.sending_api_api.SendingAPIApi()

    def tearDown(self):
        pass

    def test_send_email(self):
        """
        Test case for send_email

        Send a single email
        """
        pass

    def test_send_email_batch(self):
        """
        Test case for send_email_batch

        Send a batch of emails
        """
        pass

    def test_send_email_with_template(self):
        """
        Test case for send_email_with_template

        Send an email using a Template
        """
        pass


if __name__ == '__main__':
    unittest.main()
