# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.models.inline_response_200_days import InlineResponse200Days


class TestInlineResponse200Days(unittest.TestCase):
    """ InlineResponse200Days unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse200Days(self):
        """
        Test InlineResponse200Days
        """
        model = postmark.models.inline_response_200_days.InlineResponse200Days()


if __name__ == '__main__':
    unittest.main()
