# coding: utf-8

"""
    Postmark

    Send emails with Postmark

    OpenAPI spec version: 1.0.0
    Contact: jonathan@saharacluster.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.apis.postmark_api import PostmarkApi


class TestPostmarkApi(unittest.TestCase):
    """ PostmarkApi unit test stubs """

    def setUp(self):
        self.api = postmark.apis.postmark_api.PostmarkApi()

    def tearDown(self):
        pass

    def test_email_post(self):
        """
        Test case for email_post

        Send a single email
        """
        pass

    def test_email_with_template_post(self):
        """
        Test case for email_with_template_post

        Send an email with a template
        """
        pass


if __name__ == '__main__':
    unittest.main()
