# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.models.inline_response_200_7_inbound_rules import InlineResponse2007InboundRules


class TestInlineResponse2007InboundRules(unittest.TestCase):
    """ InlineResponse2007InboundRules unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2007InboundRules(self):
        """
        Test InlineResponse2007InboundRules
        """
        model = postmark.models.inline_response_200_7_inbound_rules.InlineResponse2007InboundRules()


if __name__ == '__main__':
    unittest.main()
