# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.apis.server_configuration_api_api import ServerConfigurationAPIApi


class TestServerConfigurationAPIApi(unittest.TestCase):
    """ ServerConfigurationAPIApi unit test stubs """

    def setUp(self):
        self.api = postmark.apis.server_configuration_api_api.ServerConfigurationAPIApi()

    def tearDown(self):
        pass

    def test_edit_current_server_configuration(self):
        """
        Test case for edit_current_server_configuration

        Edit Server Configuration
        """
        pass

    def test_get_current_server_configuration(self):
        """
        Test case for get_current_server_configuration

        Get Server Configuration
        """
        pass


if __name__ == '__main__':
    unittest.main()
