# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.apis.tag_triggers_api_api import TagTriggersAPIApi


class TestTagTriggersAPIApi(unittest.TestCase):
    """ TagTriggersAPIApi unit test stubs """

    def setUp(self):
        self.api = postmark.apis.tag_triggers_api_api.TagTriggersAPIApi()

    def tearDown(self):
        pass

    def test_create_tag_trigger(self):
        """
        Test case for create_tag_trigger

        Create a trigger for a tag
        """
        pass

    def test_delete_tag_trigger(self):
        """
        Test case for delete_tag_trigger

        Delete a single trigger
        """
        pass

    def test_edit_tag_trigger(self):
        """
        Test case for edit_tag_trigger

        Edit a single trigger
        """
        pass

    def test_get_single_tag_trigger(self):
        """
        Test case for get_single_tag_trigger

        Get a single trigger
        """
        pass

    def test_searcg_tag_triggers(self):
        """
        Test case for searcg_tag_triggers

        Search triggers
        """
        pass


if __name__ == '__main__':
    unittest.main()
