# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import postmark
from postmark.rest import ApiException
from postmark.models.inline_response_200_2 import InlineResponse2002


class TestInlineResponse2002(unittest.TestCase):
    """ InlineResponse2002 unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInlineResponse2002(self):
        """
        Test InlineResponse2002
        """
        model = postmark.models.inline_response_200_2.InlineResponse2002()


if __name__ == '__main__':
    unittest.main()
