# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class Attachment(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, content=None, content_type=None, content_id=None):
        """
        Attachment - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'content': 'str',
            'content_type': 'str',
            'content_id': 'str'
        }

        self.attribute_map = {
            'name': 'Name',
            'content': 'Content',
            'content_type': 'ContentType',
            'content_id': 'ContentID'
        }

        self._name = None
        self._content = None
        self._content_type = None
        self._content_id = None

        # TODO: let required properties as mandatory parameter in the constructor.
        #       - to check if required property is not None (e.g. by calling setter)
        #       - ApiClient.__deserialize_model has to be adapted as well
        if name is not None:
          self.name = name
        if content is not None:
          self.content = content
        if content_type is not None:
          self.content_type = content_type
        if content_id is not None:
          self.content_id = content_id

    @property
    def name(self):
        """
        Gets the name of this Attachment.

        :return: The name of this Attachment.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this Attachment.

        :param name: The name of this Attachment.
        :type: str
        """

        self._name = name

    @property
    def content(self):
        """
        Gets the content of this Attachment.

        :return: The content of this Attachment.
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """
        Sets the content of this Attachment.

        :param content: The content of this Attachment.
        :type: str
        """

        self._content = content

    @property
    def content_type(self):
        """
        Gets the content_type of this Attachment.

        :return: The content_type of this Attachment.
        :rtype: str
        """
        return self._content_type

    @content_type.setter
    def content_type(self, content_type):
        """
        Sets the content_type of this Attachment.

        :param content_type: The content_type of this Attachment.
        :type: str
        """

        self._content_type = content_type

    @property
    def content_id(self):
        """
        Gets the content_id of this Attachment.

        :return: The content_id of this Attachment.
        :rtype: str
        """
        return self._content_id

    @content_id.setter
    def content_id(self, content_id):
        """
        Sets the content_id of this Attachment.

        :param content_id: The content_id of this Attachment.
        :type: str
        """

        self._content_id = content_id

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, Attachment):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
