# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class DeliveryStatsResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, inactive_mails=None, bounces=None):
        """
        DeliveryStatsResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'inactive_mails': 'int',
            'bounces': 'list[BounceCountElement]'
        }

        self.attribute_map = {
            'inactive_mails': 'InactiveMails',
            'bounces': 'Bounces'
        }

        self._inactive_mails = None
        self._bounces = None

        # TODO: let required properties as mandatory parameter in the constructor.
        #       - to check if required property is not None (e.g. by calling setter)
        #       - ApiClient.__deserialize_model has to be adapted as well
        if inactive_mails is not None:
          self.inactive_mails = inactive_mails
        if bounces is not None:
          self.bounces = bounces

    @property
    def inactive_mails(self):
        """
        Gets the inactive_mails of this DeliveryStatsResponse.

        :return: The inactive_mails of this DeliveryStatsResponse.
        :rtype: int
        """
        return self._inactive_mails

    @inactive_mails.setter
    def inactive_mails(self, inactive_mails):
        """
        Sets the inactive_mails of this DeliveryStatsResponse.

        :param inactive_mails: The inactive_mails of this DeliveryStatsResponse.
        :type: int
        """

        self._inactive_mails = inactive_mails

    @property
    def bounces(self):
        """
        Gets the bounces of this DeliveryStatsResponse.

        :return: The bounces of this DeliveryStatsResponse.
        :rtype: list[BounceCountElement]
        """
        return self._bounces

    @bounces.setter
    def bounces(self, bounces):
        """
        Sets the bounces of this DeliveryStatsResponse.

        :param bounces: The bounces of this DeliveryStatsResponse.
        :type: list[BounceCountElement]
        """

        self._bounces = bounces

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, DeliveryStatsResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
