# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExtendedMessageOpenEventInformationClient(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, name=None, company=None, family=None):
        """
        ExtendedMessageOpenEventInformationClient - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'name': 'str',
            'company': 'str',
            'family': 'str'
        }

        self.attribute_map = {
            'name': 'Name',
            'company': 'Company',
            'family': 'Family'
        }

        self._name = None
        self._company = None
        self._family = None

        # TODO: let required properties as mandatory parameter in the constructor.
        #       - to check if required property is not None (e.g. by calling setter)
        #       - ApiClient.__deserialize_model has to be adapted as well
        if name is not None:
          self.name = name
        if company is not None:
          self.company = company
        if family is not None:
          self.family = family

    @property
    def name(self):
        """
        Gets the name of this ExtendedMessageOpenEventInformationClient.

        :return: The name of this ExtendedMessageOpenEventInformationClient.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """
        Sets the name of this ExtendedMessageOpenEventInformationClient.

        :param name: The name of this ExtendedMessageOpenEventInformationClient.
        :type: str
        """

        self._name = name

    @property
    def company(self):
        """
        Gets the company of this ExtendedMessageOpenEventInformationClient.

        :return: The company of this ExtendedMessageOpenEventInformationClient.
        :rtype: str
        """
        return self._company

    @company.setter
    def company(self, company):
        """
        Sets the company of this ExtendedMessageOpenEventInformationClient.

        :param company: The company of this ExtendedMessageOpenEventInformationClient.
        :type: str
        """

        self._company = company

    @property
    def family(self):
        """
        Gets the family of this ExtendedMessageOpenEventInformationClient.

        :return: The family of this ExtendedMessageOpenEventInformationClient.
        :rtype: str
        """
        return self._family

    @family.setter
    def family(self, family):
        """
        Sets the family of this ExtendedMessageOpenEventInformationClient.

        :param family: The family of this ExtendedMessageOpenEventInformationClient.
        :type: str
        """

        self._family = family

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExtendedMessageOpenEventInformationClient):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
