# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2003(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, opens=None, unique=None, days=None):
        """
        InlineResponse2003 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'opens': 'int',
            'unique': 'int',
            'days': 'list[InlineResponse2003Days]'
        }

        self.attribute_map = {
            'opens': 'Opens',
            'unique': 'Unique',
            'days': 'Days'
        }

        self._opens = None
        self._unique = None
        self._days = None

        # TODO: let required properties as mandatory parameter in the constructor.
        #       - to check if required property is not None (e.g. by calling setter)
        #       - ApiClient.__deserialize_model has to be adapted as well
        if opens is not None:
          self.opens = opens
        if unique is not None:
          self.unique = unique
        if days is not None:
          self.days = days

    @property
    def opens(self):
        """
        Gets the opens of this InlineResponse2003.

        :return: The opens of this InlineResponse2003.
        :rtype: int
        """
        return self._opens

    @opens.setter
    def opens(self, opens):
        """
        Sets the opens of this InlineResponse2003.

        :param opens: The opens of this InlineResponse2003.
        :type: int
        """

        self._opens = opens

    @property
    def unique(self):
        """
        Gets the unique of this InlineResponse2003.

        :return: The unique of this InlineResponse2003.
        :rtype: int
        """
        return self._unique

    @unique.setter
    def unique(self, unique):
        """
        Sets the unique of this InlineResponse2003.

        :param unique: The unique of this InlineResponse2003.
        :type: int
        """

        self._unique = unique

    @property
    def days(self):
        """
        Gets the days of this InlineResponse2003.

        :return: The days of this InlineResponse2003.
        :rtype: list[InlineResponse2003Days]
        """
        return self._days

    @days.setter
    def days(self, days):
        """
        Sets the days of this InlineResponse2003.

        :param days: The days of this InlineResponse2003.
        :type: list[InlineResponse2003Days]
        """

        self._days = days

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2003):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
