# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class InlineResponse2002(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, tracked=None, days=None):
        """
        InlineResponse2002 - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'tracked': 'int',
            'days': 'list[InlineResponse2002Days]'
        }

        self.attribute_map = {
            'tracked': 'Tracked',
            'days': 'Days'
        }

        self._tracked = None
        self._days = None

        # TODO: let required properties as mandatory parameter in the constructor.
        #       - to check if required property is not None (e.g. by calling setter)
        #       - ApiClient.__deserialize_model has to be adapted as well
        if tracked is not None:
          self.tracked = tracked
        if days is not None:
          self.days = days

    @property
    def tracked(self):
        """
        Gets the tracked of this InlineResponse2002.

        :return: The tracked of this InlineResponse2002.
        :rtype: int
        """
        return self._tracked

    @tracked.setter
    def tracked(self, tracked):
        """
        Sets the tracked of this InlineResponse2002.

        :param tracked: The tracked of this InlineResponse2002.
        :type: int
        """

        self._tracked = tracked

    @property
    def days(self):
        """
        Gets the days of this InlineResponse2002.

        :return: The days of this InlineResponse2002.
        :rtype: list[InlineResponse2002Days]
        """
        return self._days

    @days.setter
    def days(self, days):
        """
        Sets the days of this InlineResponse2002.

        :param days: The days of this InlineResponse2002.
        :type: list[InlineResponse2002Days]
        """

        self._days = days

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, InlineResponse2002):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
