# coding: utf-8

"""
    Postmark API

    Postmark makes sending and receiving email incredibly easy. 

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class MessageOpenSearchResponse(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, total_count=None, opens=None):
        """
        MessageOpenSearchResponse - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'total_count': 'int',
            'opens': 'list[ExtendedMessageOpenEventInformation]'
        }

        self.attribute_map = {
            'total_count': 'TotalCount',
            'opens': 'Opens'
        }

        self._total_count = None
        self._opens = None

        # TODO: let required properties as mandatory parameter in the constructor.
        #       - to check if required property is not None (e.g. by calling setter)
        #       - ApiClient.__deserialize_model has to be adapted as well
        if total_count is not None:
          self.total_count = total_count
        if opens is not None:
          self.opens = opens

    @property
    def total_count(self):
        """
        Gets the total_count of this MessageOpenSearchResponse.

        :return: The total_count of this MessageOpenSearchResponse.
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """
        Sets the total_count of this MessageOpenSearchResponse.

        :param total_count: The total_count of this MessageOpenSearchResponse.
        :type: int
        """

        self._total_count = total_count

    @property
    def opens(self):
        """
        Gets the opens of this MessageOpenSearchResponse.

        :return: The opens of this MessageOpenSearchResponse.
        :rtype: list[ExtendedMessageOpenEventInformation]
        """
        return self._opens

    @opens.setter
    def opens(self, opens):
        """
        Sets the opens of this MessageOpenSearchResponse.

        :param opens: The opens of this MessageOpenSearchResponse.
        :type: list[ExtendedMessageOpenEventInformation]
        """

        self._opens = opens

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, MessageOpenSearchResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
